[package]
name = "urlshortener"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.28"
tokio = {version = "1.32.0", features = ["full"]}
mongodb = {version = "3.2.0"}
base62 = "2.2.1"
serde = "1.0.217"
serde_json = "1.0.138"
dotenv = "0.15.0"
